services:
  api:
    build:
      context: .
      target: backend

    ports:
      - "8002:8000"

    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
    restart: unless-stopped

  ui:
    build:
      context: .
      target: ui

    ports:
      - "8501:8501"

    environment:
      API_BASE_URL: http://api:8000

    depends_on:
      - api

    restart: unless-stopped